In [2]:
import numpy as np

In [33]:
#qu1 farenheit to celsius
farh=np.empty(5)
cel=np.array([77,100,103,104,105])
for i in range(5):
    val=((cel[i]-32)*(5/9))
    farh[i]=val
print("Array in celsius",cel)
print("Array in farenheit",farh)

Array in celsius [ 77 100 103 104 105]
Array in farenheit [25.         37.77777778 39.44444444 40.         40.55555556]


In [34]:
#qu2 sum,avg,variance and SD of values in a random array
arr1=np.random.randint(1,100,1000)
avg=np.sum(arr1)/1000
print("Average=",avg)
sd=np.std(arr1)
var=np.var(arr1)
print("Standard Deviation=",sd)
print("Variance=",var)

Average= 51.472
Standard Deviation= 28.563074344334858
Variance= 815.8492160000001


In [35]:
#qu3 conversion of degrees to radians
dgr=[30,60,90,180,360]
rad=np.deg2rad(dgr)
print(rad)

[0.52359878 1.04719755 1.57079633 3.14159265 6.28318531]


In [36]:
#qu4 differnce between array elements
arr2=np.array([10,11,23,10,33,55])
for i in range(len(arr2)-1):
    diffr=arr2[i]-arr2[i+1]
    print("Difference of element ",i,"and element ",i+1,"is ",diffr)
    

Difference of element  0 and element  1 is  -1
Difference of element  1 and element  2 is  -12
Difference of element  2 and element  3 is  13
Difference of element  3 and element  4 is  -23
Difference of element  4 and element  5 is  -22


In [70]:
#qu5 sort complex array
com=np.array([17+2j,13+5j,11+45j,18+89j,15+45j])
print(com)
com_sorted=np.sort_complex(com)
print(com_sorted)

[17. +2.j 13. +5.j 11.+45.j 18.+89.j 15.+45.j]
[11.+45.j 13. +5.j 15.+45.j 17. +2.j 18.+89.j]


In [37]:
#qu6 print values greater than 4 from a random valued array
rand_arr=np.random.randint(1,20,10)
print(rand_arr)
for i in range(len(rand_arr)):
    if rand_arr[i]>4:
        print(rand_arr[i])

[10 18 16 11 11 15 13 12 12  3]
10
18
16
11
11
15
13
12
12


In [38]:
#qu7 array search
srch_arr=np.array([11,22,33,44,55])
srch=int(input("Enter a element to search:"))
x=np.where(srch_arr==srch)
if (srch in x[0]):
    print("empty")
else:
    print("Number found at the position",*x[0]+1)

Number found at the position 2


In [39]:
#qu8 save array to textfile and load it
arr1=np.array([11,22,33,44,55])
arr1.tofile("arr.txt",sep=",")
arr2=np.loadtxt('arr.txt',delimiter=",")
print(arr2)

[11. 22. 33. 44. 55.]


In [40]:
#qu9 array of even values from 30 to 60 
arr1=np.arange(30,60,2)
print(arr1)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]


In [30]:
#qu10 sum of elements,sum pof rows,sum of columns
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
sum=np.sum(arr2)
print(sum)
rsum=np.sum(arr2,axis=0)
print("Sum of rows=",rsum)
csum=np.sum(arr2,axis=1)
print("Sum of rows=",csum)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
Sum of rows= [12 15 18]
Sum of rows= [ 6 15 24]
