In [2]:
import numpy as np

In [ ]:
#creating normal tuple
a=(11,22,33,44,55)
print(type(a))

<class 'tuple'>


In [ ]:
#creating numpy.ndarray
arr1=np.array(a)
print(arr1)
print(type(arr1))
arr2=np.array([11,22,33,44])
print(arr2)
print(type(arr2))

[11 22 33 44 55]
<class 'numpy.ndarray'>
[11 22 33 44]
<class 'numpy.ndarray'>


In [14]:
arr3=np.arange(1,100,2)
print(arr3)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [24]:
arr4=np.zeros(5)
print(arr4)
arr5=np.ones(5)
print(arr5)
arr6=np.zeros((3,3),int)
print(arr6)


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [31]:
mat1=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(mat1)
mat2=np.eye(3)
print(mat2)
mat3=np.identity(3)
print(mat3)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr7=np.arange(11)
print(arr7)
print(arr7[:5])
print(arr7[::5])
print(arr7[5:])
print(arr7[1:5])
print(arr7[-4:-1])
print(arr7[::-1])
arr8=np.copy(arr7)
print(arr8)
print(arr8[3])
arr7[2]=7
print(arr7)
print(arr8)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[ 0  5 10]
[ 5  6  7  8  9 10]
[1 2 3 4]
[7 8 9]
[10  9  8  7  6  5  4  3  2  1  0]
[ 0  1  2  3  4  5  6  7  8  9 10]
3
[ 0  1  7  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [56]:
#concatenating 2 arrays
ar1=np.array((1,2,3,4,5))
ar2=np.array((6,7,8,9))
ar3=np.concatenate((ar1,ar2))
print(ar3)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#concatenating 2 matrices
m1=np.array([[1,2,3],[4,5,6]])
m2=np.array([[11,22,33],[44,55,66]])
#concatenating 2 matrices with axis=0
m3=np.concatenate((m1,m2),axis=0)
#concatenating 2 matrices with axis=1
m4=np.concatenate((m1,m2),axis=1)
m5=np.concatenate((m1,m2))
print(m3)
print(m4)
print(m5)

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]
[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]


In [101]:
m6=np.array([1,2,3,7,5,6,7])
print(m6)
x=np.where(m6==7)
print(x)
if(7 in x[0]):
    print("empty")
else:
    print("Number found at the position",*x[0]+1)

[1 2 3 7 5 6 7]
(array([3, 6], dtype=int64),)
Number found at the position 4 7
